# extraction/extractor.py
# DAY 2 — Local invoice extraction using PyMuPDF text parsing (no API, no cost)
#
# Strategy: the invoices are generated by ReportLab, so they contain embedded
# selectable text. PyMuPDF extracts that text as-is; regex patterns then pull
# each field from the known label format written by generate_documents.py.
# This is 100% free, instant, and works offline.

import json
import re
from pathlib import Path


def _extract_text(pdf_path: str) -> str:
    """Return the full text of the first page of a PDF using PyMuPDF."""
    try:
        import fitz  # PyMuPDF
    except ImportError:
        raise ImportError("pymupdf is required: pip install pymupdf")

    doc  = fitz.open(pdf_path)
    text = doc[0].get_text("text")   # plain text, preserves newlines
    doc.close()
    return text


def _safe_float(value: str | None) -> float | None:
    """Convert a string like '1,23,456.78' to float, or return None."""
    if value is None:
        return None
    cleaned = value.replace(",", "").strip()
    try:
        return float(cleaned)
    except ValueError:
        return None


def _parse_invoice(text: str, source_file: str) -> dict:
    """
    Parse a ReportLab-generated invoice using regex patterns that match the
    exact label strings written by generate_documents.py.
    """

    def find(pattern: str, default=None):
        m = re.search(pattern, text)
        return m.group(1).strip() if m else default

    # ── Header ────────────────────────────────────────────────────────────────
    # "INV-0001" appears top-right in the teal header band
    invoice_number = find(r"(INV-\d{4})")

    # "Date: 2024-08-15" — also in the header
    invoice_date = find(r"Date:\s*(\d{4}-\d{2}-\d{2}|\d{2}[/-]\d{2}[/-]\d{4}|\d{2}-\w{3}-\d{4})")

    # ── Vendor block (under "FROM (Vendor)") ──────────────────────────────────
    # The vendor name is the first non-empty line after "FROM (Vendor)"
    vendor_name = find(r"FROM \(Vendor\)\s*\n([^\n]+)")

    # "GSTIN: 27AABC12345Z1Z6"
    vendor_gstin = find(r"GSTIN:\s*([A-Z0-9]{10,20})")

    # Line after GSTIN is the address (may be truncated to 60 chars)
    vendor_address = find(r"GSTIN:[^\n]+\n([^\n]{5,})")

    # "Bank A/C: XXXXXXXXXX"
    bank_account = find(r"Bank A/C:\s*([^\n]+)")

    # ── PO & payment ──────────────────────────────────────────────────────────
    po_reference   = find(r"(PO-\d{4})")
    payment_terms  = find(r"Payment Terms:\s*(Net \d+)")

    # ── Line items ────────────────────────────────────────────────────────────
    # Format: <description>  <qty>  <rate>  <amount>
    # The header row labels are Description / Qty / Rate / Amount
    # Actual data line: any text,  then digits for qty, then two decimals
    line_items = []
    li_pattern = re.compile(
        r"^(?!Description|Subtotal|CGST|SGST|Total)(.{5,45}?)\s+"
        r"(\d{1,3})\s+"
        r"([\d,]+\.\d{2})\s+"
        r"([\d,]+\.\d{2})",
        re.MULTILINE,
    )
    for m in li_pattern.finditer(text):
        line_items.append({
            "description": m.group(1).strip(),
            "quantity":    int(m.group(2)),
            "unit_rate":   _safe_float(m.group(3)),
            "amount":      _safe_float(m.group(4)),
        })

    # ── Totals ────────────────────────────────────────────────────────────────
    # "Subtotal :  45,200.00"  — value appears at end of the same line
    subtotal = _safe_float(find(r"Subtotal\s*:\s*([\d,]+\.\d{2})"))
    cgst     = _safe_float(find(r"CGST[^:]*:\s*([\d,]+\.\d{2})"))
    sgst     = _safe_float(find(r"SGST[^:]*:\s*([\d,]+\.\d{2})"))
    igst     = _safe_float(find(r"IGST[^:]*:\s*([\d,]+\.\d{2})"))   # may not exist

    # "Total (INR):   54,434.00"
    total_amount = _safe_float(find(r"Total\s*\(INR\):\s*([\d,]+\.\d{2})"))

    # ── Fallback: derive subtotal / total if regex missed ────────────────────
    if subtotal is None and line_items:
        subtotal = sum(li["amount"] for li in line_items if li["amount"])
    if total_amount is None and subtotal is not None:
        total_amount = round(
            (subtotal or 0) + (cgst or 0) + (sgst or 0) + (igst or 0), 2
        )

    return {
        "invoice_number":  invoice_number,
        "po_reference":    po_reference,
        "invoice_date":    invoice_date,
        "vendor_name":     vendor_name,
        "vendor_gstin":    vendor_gstin,
        "vendor_address":  vendor_address,
        "line_items":      line_items,
        "subtotal":        subtotal,
        "cgst":            cgst,
        "sgst":            sgst,
        "igst":            igst,
        "total_amount":    total_amount,
        "payment_terms":   payment_terms,
        "bank_account":    bank_account,
        "currency":        "INR",
        "source_file":     source_file,
    }


def extract_invoice_data(pdf_path: str) -> dict:
    """
    Extract structured data from a ReportLab-generated invoice PDF.
    Uses PyMuPDF text extraction + regex — no API key required.

    Args:
        pdf_path: Path to the invoice PDF file

    Returns:
        Dictionary with extracted invoice fields (same schema as before)
    """
    text   = _extract_text(pdf_path)
    result = _parse_invoice(text, Path(pdf_path).name)
    return result


if __name__ == "__main__":
    import sys
    test_path = sys.argv[1] if len(sys.argv) > 1 else "data/invoices/INV-0001.pdf"
    import os
    if os.path.exists(test_path):
        print(f"Extracting {test_path}...\n")
        result = extract_invoice_data(test_path)
        print(json.dumps(result, indent=2))
    else:
        print("Usage: python extraction/extractor.py data/invoices/INV-0001.pdf")